name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # Change to branch in use

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.5 # Match Ruby version
        bundler-cache: true

    - name: Install Dependencies
      run: bundle install

    - name: Build Jekyll Site
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site